# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/walker2/Projects/Hexxagon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/walker2/Projects/Hexxagon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/walker2/Projects/Hexxagon/CMakeFiles /home/walker2/Projects/Hexxagon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/walker2/Projects/Hexxagon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Hexxagon

# Build rule for target.
Hexxagon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Hexxagon
.PHONY : Hexxagon

# fast build rule for target.
Hexxagon/fast:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/build
.PHONY : Hexxagon/fast

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Board.cpp.s
.PHONY : Board.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameGUI.o: GameGUI.cpp.o

.PHONY : GameGUI.o

# target to build an object file
GameGUI.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/GameGUI.cpp.o
.PHONY : GameGUI.cpp.o

GameGUI.i: GameGUI.cpp.i

.PHONY : GameGUI.i

# target to preprocess a source file
GameGUI.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/GameGUI.cpp.i
.PHONY : GameGUI.cpp.i

GameGUI.s: GameGUI.cpp.s

.PHONY : GameGUI.s

# target to generate assembly for a file
GameGUI.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/GameGUI.cpp.s
.PHONY : GameGUI.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/Player.cpp.s
.PHONY : Player.cpp.s

ResourceManager.o: ResourceManager.cpp.o

.PHONY : ResourceManager.o

# target to build an object file
ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/ResourceManager.cpp.o
.PHONY : ResourceManager.cpp.o

ResourceManager.i: ResourceManager.cpp.i

.PHONY : ResourceManager.i

# target to preprocess a source file
ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/ResourceManager.cpp.i
.PHONY : ResourceManager.cpp.i

ResourceManager.s: ResourceManager.cpp.s

.PHONY : ResourceManager.s

# target to generate assembly for a file
ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/ResourceManager.cpp.s
.PHONY : ResourceManager.cpp.s

States/Difficulty_Computerwars_State.o: States/Difficulty_Computerwars_State.cpp.o

.PHONY : States/Difficulty_Computerwars_State.o

# target to build an object file
States/Difficulty_Computerwars_State.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Difficulty_Computerwars_State.cpp.o
.PHONY : States/Difficulty_Computerwars_State.cpp.o

States/Difficulty_Computerwars_State.i: States/Difficulty_Computerwars_State.cpp.i

.PHONY : States/Difficulty_Computerwars_State.i

# target to preprocess a source file
States/Difficulty_Computerwars_State.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Difficulty_Computerwars_State.cpp.i
.PHONY : States/Difficulty_Computerwars_State.cpp.i

States/Difficulty_Computerwars_State.s: States/Difficulty_Computerwars_State.cpp.s

.PHONY : States/Difficulty_Computerwars_State.s

# target to generate assembly for a file
States/Difficulty_Computerwars_State.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Difficulty_Computerwars_State.cpp.s
.PHONY : States/Difficulty_Computerwars_State.cpp.s

States/Difficulty_Singleplayer_State.o: States/Difficulty_Singleplayer_State.cpp.o

.PHONY : States/Difficulty_Singleplayer_State.o

# target to build an object file
States/Difficulty_Singleplayer_State.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Difficulty_Singleplayer_State.cpp.o
.PHONY : States/Difficulty_Singleplayer_State.cpp.o

States/Difficulty_Singleplayer_State.i: States/Difficulty_Singleplayer_State.cpp.i

.PHONY : States/Difficulty_Singleplayer_State.i

# target to preprocess a source file
States/Difficulty_Singleplayer_State.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Difficulty_Singleplayer_State.cpp.i
.PHONY : States/Difficulty_Singleplayer_State.cpp.i

States/Difficulty_Singleplayer_State.s: States/Difficulty_Singleplayer_State.cpp.s

.PHONY : States/Difficulty_Singleplayer_State.s

# target to generate assembly for a file
States/Difficulty_Singleplayer_State.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Difficulty_Singleplayer_State.cpp.s
.PHONY : States/Difficulty_Singleplayer_State.cpp.s

States/Intro_State.o: States/Intro_State.cpp.o

.PHONY : States/Intro_State.o

# target to build an object file
States/Intro_State.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Intro_State.cpp.o
.PHONY : States/Intro_State.cpp.o

States/Intro_State.i: States/Intro_State.cpp.i

.PHONY : States/Intro_State.i

# target to preprocess a source file
States/Intro_State.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Intro_State.cpp.i
.PHONY : States/Intro_State.cpp.i

States/Intro_State.s: States/Intro_State.cpp.s

.PHONY : States/Intro_State.s

# target to generate assembly for a file
States/Intro_State.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Intro_State.cpp.s
.PHONY : States/Intro_State.cpp.s

States/Menu_State.o: States/Menu_State.cpp.o

.PHONY : States/Menu_State.o

# target to build an object file
States/Menu_State.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Menu_State.cpp.o
.PHONY : States/Menu_State.cpp.o

States/Menu_State.i: States/Menu_State.cpp.i

.PHONY : States/Menu_State.i

# target to preprocess a source file
States/Menu_State.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Menu_State.cpp.i
.PHONY : States/Menu_State.cpp.i

States/Menu_State.s: States/Menu_State.cpp.s

.PHONY : States/Menu_State.s

# target to generate assembly for a file
States/Menu_State.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Menu_State.cpp.s
.PHONY : States/Menu_State.cpp.s

States/Multiplayer_State.o: States/Multiplayer_State.cpp.o

.PHONY : States/Multiplayer_State.o

# target to build an object file
States/Multiplayer_State.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Multiplayer_State.cpp.o
.PHONY : States/Multiplayer_State.cpp.o

States/Multiplayer_State.i: States/Multiplayer_State.cpp.i

.PHONY : States/Multiplayer_State.i

# target to preprocess a source file
States/Multiplayer_State.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Multiplayer_State.cpp.i
.PHONY : States/Multiplayer_State.cpp.i

States/Multiplayer_State.s: States/Multiplayer_State.cpp.s

.PHONY : States/Multiplayer_State.s

# target to generate assembly for a file
States/Multiplayer_State.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/States/Multiplayer_State.cpp.s
.PHONY : States/Multiplayer_State.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Hexxagon.dir/build.make CMakeFiles/Hexxagon.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Hexxagon"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameGUI.o"
	@echo "... GameGUI.i"
	@echo "... GameGUI.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... ResourceManager.o"
	@echo "... ResourceManager.i"
	@echo "... ResourceManager.s"
	@echo "... States/Difficulty_Computerwars_State.o"
	@echo "... States/Difficulty_Computerwars_State.i"
	@echo "... States/Difficulty_Computerwars_State.s"
	@echo "... States/Difficulty_Singleplayer_State.o"
	@echo "... States/Difficulty_Singleplayer_State.i"
	@echo "... States/Difficulty_Singleplayer_State.s"
	@echo "... States/Intro_State.o"
	@echo "... States/Intro_State.i"
	@echo "... States/Intro_State.s"
	@echo "... States/Menu_State.o"
	@echo "... States/Menu_State.i"
	@echo "... States/Menu_State.s"
	@echo "... States/Multiplayer_State.o"
	@echo "... States/Multiplayer_State.i"
	@echo "... States/Multiplayer_State.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

