#ifndef HEXXAGON_GAMESTATES_H
#define HEXXAGON_GAMESTATES_H
enum class GameStates
{
    INTRO = 0,
    MENU,
    MULTIPLAYER,
    DIFFICULTY_SINGLEPLAYER,
    DIFFICULTY_COMPUTERWARS,
    SINGLEPLAYER,
    COMPUTERWARS,
    EXIT,
    NONE
} ;
#endif
